# Generated by Django 5.1.5 on 2025-01-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='step',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
