# Generated by Django 5.1.5 on 2025-02-06 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_alter_step_options_step_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.course')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
